# Generated by Django 3.1.4 on 2020-12-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена продукта')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Скидка на продукт')),
                ('description', models.TextField(max_length=400, verbose_name='Описание продукта')),
                ('quantity', models.IntegerField(verbose_name='Колличество продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
