# Generated by Django 3.1.4 on 2020-12-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='chat_id',
            field=models.BigIntegerField(default=0, null=True, verbose_name='Айди чата пользователя'),
        ),
    ]
