# Generated by Django 3.1.4 on 2020-12-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20201214_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(verbose_name='Айди чата пользователя')),
                ('date_ban', models.DateField(auto_now_add=True, verbose_name='Дата бана')),
                ('days_ban', models.IntegerField(verbose_name='Колличество дней бана')),
                ('expiration_date', models.DateField(verbose_name='Дата истечения бана')),
                ('reason_ban', models.CharField(max_length=20, verbose_name='Причина бана')),
            ],
            options={
                'verbose_name': 'Черный список',
                'verbose_name_plural': 'Черный список',
            },
        ),
    ]
