# Generated by Django 3.1.4 on 2020-12-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_blacklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklist',
            options={'verbose_name': 'Черный список', 'verbose_name_plural': 'Черный список пользователей'},
        ),
    ]
