# Generated by Django 3.1.4 on 2020-12-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20201215_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
