# Generated by Django 3.1.4 on 2020-12-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_userprofile_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistusers',
            name='expiration_date',
            field=models.DateField(blank=True, verbose_name='Дата истечения бана'),
        ),
    ]
