# Generated by Django 3.1.4 on 2020-12-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20201215_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(default=0, null=True, verbose_name='Айди чата пользователя')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Пользователь в очередь',
                'verbose_name_plural': 'Очередь пользователей',
            },
        ),
    ]
