# Generated by Django 3.1.4 on 2020-12-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_userqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistusers',
            name='days_ban',
            field=models.IntegerField(blank=True, verbose_name='Колличество дней бана'),
        ),
        migrations.AlterField(
            model_name='blacklistusers',
            name='reason_ban',
            field=models.CharField(blank=True, max_length=500, verbose_name='Причина бана'),
        ),
    ]
